name: 🐞 Bug report
description: File a bug report
labels: [kind/bug]
title: "🐞 <title>"
body:
  - type: markdown
    attributes:
      value: |
        Please check if this bug has [already been reported](./).
  - type: textarea
    id: what-happened
    attributes:
      label: What is the issue?
      description: What happened? What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: log-output
    attributes:
      label: Log output
      description: Please paste the log output
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: What are the steps that we need to follow to reproduce this issue?
    validations:
      required: false
  - type: input
    id: saivvy-version
    attributes:
      label: Software version
      description: If available, please provide the software version
      placeholder: e.g. perception 0.1.2 (fead547d) 
    validations:
      required: false
  - type: input
    id: docker-version
    attributes:
      label: Docker image version
      description: Which Saivvy's docker image are you running the software on?
      placeholder: e.g. ghcr.io/saivvy/perception-20.04-jp4.6-amd64  latest    bd6e912bc3ce
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        We appreciate you taking the time to report a bug.
        If you want to become a Saivvy contributor and submit this improvement, we will appreciate it even more.

        [You can become a contributor in less than 10 minutes](https://github.com/saivvy/.github/blob/main/CONTRIBUTING.md).
        If you try it out and it doesn't live up to this promise, we definitely want to know what would have made it better.
        All Saivvy contributors will be forever grateful to you 🙌
